# type: ignore
from devkit.generators.ext.sanic_handler_generator import SanicHandlerGenerator
from devkit.generators.ext.sql_model_generator import SqlModelGenerator
from devkit.generators.ext.sql_class_definition_generator import SqlClassDefinitionGenerator
